run:
  timeout: 5m
 
issues:
  exclude-dirs:
    - "^github\\.com($|/)"
    - "^bin($|/)"
  exclude-files:
    - "proto/oms/v1/.*\\.pb\\.go$"

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - errcheck
    - gofmt

linters-settings:
  gofmt:
    simplify: true
